apiVersion: batch/v1
kind: Job
metadata:
  name: media-migrate
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:bookworm
          command: ["sh", "-c", "until pg_isready -h postgres-cluster-rw -p 5432; do sleep 2; done"]
      containers:
        - name: migrate
          image: postgres:bookworm
          command: ["psql", "$(DATABASE_URL)", "-f", "/migrations/schema.sql"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-cluster-app
                  key: uri
          volumeMounts:
            - name: migrations
              mountPath: /migrations
      # to create this volume, create a configmap from the file 'schema.sql'  
      volumes:
        - name: migrations
          configMap:
            name: media-migrations
      restartPolicy: Never