// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package pgsql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRecord = `-- name: CreateRecord :one
INSERT INTO records (
  id, filename, mime_type, size, path, uploaded_at, user_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, filename, mime_type, size, path, user_id, uploaded_at
`

type CreateRecordParams struct {
	ID         uuid.UUID
	Filename   string
	MimeType   string
	Size       int64
	Path       string
	UploadedAt time.Time
	UserID     uuid.UUID
}

func (q *Queries) CreateRecord(ctx context.Context, arg CreateRecordParams) (Record, error) {
	row := q.db.QueryRow(ctx, createRecord,
		arg.ID,
		arg.Filename,
		arg.MimeType,
		arg.Size,
		arg.Path,
		arg.UploadedAt,
		arg.UserID,
	)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.MimeType,
		&i.Size,
		&i.Path,
		&i.UserID,
		&i.UploadedAt,
	)
	return i, err
}

const deleteRecord = `-- name: DeleteRecord :exec
DELETE FROM records
WHERE id = $1 AND user_id = $2
`

type DeleteRecordParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteRecord(ctx context.Context, arg DeleteRecordParams) error {
	_, err := q.db.Exec(ctx, deleteRecord, arg.ID, arg.UserID)
	return err
}

const getRecord = `-- name: GetRecord :one
SELECT id, filename, mime_type, size, path, user_id, uploaded_at FROM records
WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetRecordParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetRecord(ctx context.Context, arg GetRecordParams) (Record, error) {
	row := q.db.QueryRow(ctx, getRecord, arg.ID, arg.UserID)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.MimeType,
		&i.Size,
		&i.Path,
		&i.UserID,
		&i.UploadedAt,
	)
	return i, err
}

const listRecords = `-- name: ListRecords :many
SELECT id, filename, mime_type, size, path, user_id, uploaded_at FROM records WHERE user_id = $1
`

func (q *Queries) ListRecords(ctx context.Context, userID uuid.UUID) ([]Record, error) {
	rows, err := q.db.Query(ctx, listRecords, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Record
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.MimeType,
			&i.Size,
			&i.Path,
			&i.UserID,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
