// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgsql

import (
	"time"

	"github.com/google/uuid"
)

type Record struct {
	ID         uuid.UUID
	Filename   string
	MimeType   string
	Size       int64
	Path       string
	CreatedAt  time.Time
	UploadedAt time.Time
}
